name: Build Check

on:
  pull_request:
    branches: [main, release, develop]

jobs:
  build:
    strategy:
      matrix:
        go-version: [ 1.17.x, 1.18.x ]
        os: [ ubuntu-latest ]
        entrypoint: [ "main.go" ]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Go Module Download
        run: go mod download

      - name : Build Check
        run: go build  ${{ matrix.entrypoint }}
